/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class ImagesRes {
  ImagesRes._();

  static const String PLUGIN_NAME = 'task';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String FLAG_OF_SAUDI_ARABIA = 'images/flag-of-saudi-arabia.png';
  static const String SAUDI_ARABIA_FLAG = 'images/saudi-arabia-flag.png';
}
